config/routes.rb
SienaCsl::Application.routes.draw do





#http verbs are:
#get, post(create new item), put(replace existing item), patch(update existing item), delete(delete existing item)
#patch default for forms hidden field _method


def makeRoutes
	mount ActionCable.server => '/cable'

  resources :fuzzy_rules
  resources :chat_messages
  resources :proposed_keywords

  resources :competence_nodes

  resources :student_alu_groups

  resources :alu_groups

  resources :competence_groups

  resources :competences

  resources :related_contents

  resources :tests

  resources :answers

  resources :question_responses

  resources :node_question_relations

  resources :edges

  resources :teacher_assigns

  resources :student_assigns
  resources :grouptest_chatmessages

  resources :teachers

  resources :admins

  resources :students

  resources :courses
  resources :stopwords

  resources :works

  resources :nodes

  resources :questions

  resources :users

  get '/' => "users#getUserHome" 


  get 'login'  => 'users#login', :as => :login
  get 'logout'  => 'users#logout', :as => :logout
  get 'register'  => 'users#new', :as => :register
  get 'lost_password'  => 'users#get_lost_password', :as => :lost_password

	get 'cambiarEstado/:userid' => 'users#changeActive'
	get 'entrarComo/:userid' => 'users#loginAs'
	get 'home' => 'users#getUserHome'
	get 'ayuda' => 'users#help'
	get 'matricular_alumno/:course_id' => 'student_assigns#enroll'
	get 'matricular_profesor/:course_id' => 'teacher_assigns#enroll'
	get 'cambiar_coordinador/:id/:course_id' => 'teacher_assigns#changeCoordinator'
	get 'matricular_profesor_admin/:course_id/:teacher_id' => 'teacher_assigns#assign_to_course'
	post 'matricular_alumnos/:course_id' => 'student_assigns#register_to_course'
	get 'matricular_profesores/:course_id' => 'teacher_assigns#register_to_course'
	get 'nuevo_nodo/:course_id' => 'nodes#new'
	get 'nuevo_comp_grupo/:competence_id' => 'competence_groups#newAluGroup'
	get 'nuevo_comp_nodo/:competence_id' => 'competence_nodes#newNode'
	get 'importar_compendium/:course_id' => 'nodes#importFromCompendium'
	get 'nueva_pregunta/:course_id' => 'questions#new'
	get 'borrar_imagen/:question_id' => 'questions#deleteImgFile'
 get 'nueva_respuesta/:question_id' => 'question_responses#new'
 get 'nuevo_nodo_asoc/:question_id' => 'node_question_relations#newNode'
 get 'nueva_pregunta_asoc/:node_id' => 'node_question_relations#newQuestion'
 get 'nuevas_preguntas_delnodo/:node_id' => 'node_question_relations#newQuestionsFromNode'
 get 'nuevo_alumno/:alu_group_id' => 'student_alu_groups#newStudent'
 get 'trabajos_asignatura/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourse'
 get 'trabajos_asignatura_xml/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourseXML'
 get 'trabajos/:student_id/course_id' => 'works#listByStudent'
 get 'nuevo_trabajo/:student_id/:course_id' => 'works#new'
 get 'nodos/:course_id' => 'nodes#listByCourse' 
 get 'preguntas/:course_id' => 'questions#listByCourse' 
 get 'createIndex/:question_id' => 'questions#createIndexDbPedia' 
 get 'deleteIndex/:question_id' => 'questions#deleteIndexDbPedia' 
 get 'profesores/:course_id' => 'teacher_assigns#listByCourse' 
 get 'alumnos/:course_id' => 'student_assigns#listByCourse' 
 get 'grupos/:course_id' => 'alu_groups#listByCourse' 
 get 'profesores_no_matriculados/:course_id' => 'teacher_assigns#listByCourseNot' 
 get 'alumnos_no_matriculados/:course_id' => 'student_assigns#listByCourseNot' 
 get 'nuevo_grupo/:course_id' => 'alu_groups#new' 
 get 'grupos_de_alumnos/:student_id/:course_id' => 'alu_groups#listByStudentAndCourse' 
 get 'nuevo_predecesor/:dest_id' => 'edges#new_dest'
 get 'nuevo_sucesor/:src_id' => 'edges#new_src'
 get 'editar/:src_id/:dst_id' => 'edges#edit'
 get 'borrar/:src_id/:dst_id' => 'edges#destroy'
 get 'nuevo_contenido/:node_id' => 'related_contents#new'
 get 'html_related/:related_content_id/*filename' => 'related_contents#view_as_html'  , :filename => /.+/
 get 'asignaturas_mat' => 'courses#indexAssigned'
 get 'alumnos_en/:course_id' => 'courses#allStudents'
 get 'exportar_asignatura/:course_id' => 'courses#export'
	get 'importar_asignatura' => 'courses#import'
 get 'cambiar_tema/:theme' => 'users#changeTheme'
 get 'cambiar_idioma/:locale' => 'users#set_locale'
 get 'competencias_grupo/:alu_group_id' => 'competences#listByGroup'
 get 'competencias_grupos' => 'competences#listByGroups'
 get 'ver_chats/:username' => 'users#listChats'
 post 'ver_pregunta_alu/:question_id/:test_id' => 'questions#showAlu'

 get 'changePassword/:userid' => 'users#chPw' 
 get 'usuarios_no_activos' => 'users#indexNotActive'
 get 'nuevo_test/:work_id' => 'questions#starttest'
 get 'borrar_image_test/:test_id' => 'tests#deleteTestImage'
 get 'nuevo_trabajo_asign/:course_id/:assignedtoType' => 'works#newAll'

 get 'test/:test_id' => 'questions#test'
 patch 'contestar' => 'questions#answer'
 get 'regenerar_test_alumno/:test_id' => 'questions#regenerate_student_id'
 get 'register_to_test/:test_id' => 'tests#register_to_test'
 get 'leave_test/:test_id' => 'tests#leave_test'
 get 'cambiar_comentario/:grouptest_chatmessage_id' => 'grouptest_chatmessages#changeComment'

 get 'lista_tests/:work_id' => 'tests#listByWork'
 get 'test_xml/:test_id' => 'tests#showXML'	

 get 'subir_fichero_contenido/:related_content_id' => 'related_contents#uploadFile'
 get 'borrar_fichero_contenido/:name/:related_content_id' => 'related_contents#deleteFile'
 get 'fichero_principal_contenido/:name/:related_content_id' => 'related_contents#mainFile'
 get 'lista_contenidos/:node_id/:recover' => 'related_contents#listByNodeAndRecover'
 get 'subir_fichero_competencia/:alu_group_id/:competence_id' => 'competence_groups#uploadFile'


	#proposed keywords
	 post 'ver_keyword/:question_id/:keyword' => 'proposed_keywords#show'
	 post 'keywords_para/:question_id' => 'proposed_keywords#list'
	 post 'aceptar_keyword/:question_id/:keyword' => 'proposed_keywords#accept'
	 post 'rechazar_keyword/:question_id/:keyword' => 'proposed_keywords#reject'
	 post 'rechazar_keyword/:question_id/:keyword' => 'proposed_keywords#setnew'
	 post 'stopword_keyword/:keyword' => 'proposed_keywords#setStopword'


 get ':controller(/:action(/:id(.:format)))'
 post ':controller(/:action(/:id(.:format)))'

end

makeRoutes

#scope  '/siena2' do
#	makeRoutes
#end


end

app/models/node.rb
class Node < ActiveRecord::Base


	#changed because has_many_and_belongs_to deprecated edges deleted here, no need for before_destroy
	has_many :successors , :through => :edges_as_source, :source => :dest
	has_many :predecessors , :through => :edges_as_dest, :source => :src
	has_many :edges_as_source ,:foreign_key => 'src_id', :class_name => 'Edge',  :dependent => :delete_all, inverse_of: :src	
	has_many :edges_as_dest ,:foreign_key => 'dest_id', :class_name => 'Edge', :dependent => :delete_all, inverse_of: :dest	
	def edges
		edges_as_source + edges_as_dest
	end

	has_many :node_question_relations , :dependent => :delete_all
	has_many :questions, :through => :node_question_relations
	has_many :competences, :through => :competence_nodes
	has_many :competence_nodes , :dependent => :delete_all	
	has_many :works , :dependent => :delete_all	

	belongs_to :course
	belongs_to :teacher

	has_many :related_contents , :dependent => :delete_all	


	validates_numericality_of :minPassPoints, :only_integer => false, :message => "tiene que ser  float."
	validates_inclusion_of :minPassPoints, :in => 0..1, :message => "solo puede ser entre 0 y 1." 
	#should validate uniqueness of content and course
  validates_uniqueness_of :content  , :scope => [:course_id]




end

app/controllers/nodes_controller.rb
require 'nodes_helper'

class NodesController < ApplicationController


include NodesHelper

before_filter(:only => [:edit, :update , :destroy ] ) { |c| c.auth  [ {:types =>  [User::PROF] , :condition => lambda{|params,session| Node.find(params[:id]).teacher_id == session[:useraccount_id]} } , {:types => [User::ADMIN]} ]  }
before_filter(:only => [:new, :create , :listByCourse, :show, :importFromCompendium, :saveImportFromCompendium] ) { |c| c.auth  [ {:types =>  [User::PROF, User::ADMIN] } ]  }
 before_filter(:only => [:index] ) { |c| c.auth  [ {:types =>  [User::ADMIN]  }]  }

layout :green_web

  # GET /nodes
  # GET /nodes.xml
  def index
		@nodes = Node.includes(:course)
		if !params[:course_id].nil? && params[:course_id]!=""
			@nodes = @nodes.where(course_id: params[:course_id])
		end
		if !params[:content].nil? && params[:content]!=""
			@nodes = @nodes.where('content LIKE ?', "%#{params[:content]}%")
		end

		@nodes = @nodes.paginate(page: params[:page], per_page: 20).order(content: :asc)
  end

	def listByCourse
		@nodes = Node.where(course_id: params[:course_id])
		if !params[:content].nil? && params[:content]!=""
			@nodes = @nodes.where('content LIKE ?', "%#{params[:content]}%")
		end

		@nodes = @nodes.paginate(page: params[:page], per_page: 20).order(content: :asc)
	end


  # GET /nodes/1
  # GET /nodes/1.xml
  def show
    @node = Node.find(params[:id])
		@questions = Question.includes(:node_question_relations).where('node_question_relations.node_id = ?', @node).references(:node_question_relations).paginate(page: params[:page], per_page: 20).order('content ASC') 

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.xml
  def new
    @node = Node.new
		@node.course_id = params[:course_id]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
		@questions = Question.includes(:node_question_relations).where('node_question_relations.node_id = ?', @node).references(:node_question_relations).paginate(page: params[:page], per_page: 20).order('content ASC') 
  end

  # POST /nodes
  # POST /nodes.xml
  def create
    @node = Node.new(node_params)
	if User.find(session[:userid]).useraccount_type == User::PROF
		@node.teacher_id = session[:useraccount_id]
	else
		@node.teacher_id = Teacher.limit(1).pluck("id").first

	end
      if @node.save
        flash[:notice] = t('node_created_success')
        redirect_to edit_node_path(@node) 
      else
        render :action => "new" 
      end
  end

  # PUT /nodes/1
  # PUT /nodes/1.xml
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update(node_params)
        flash[:notice] = t('node_updated_success')
        format.html { redirect_to(@node) }
        format.xml  { head :ok }
      else
				@questions = initialize_grid(Question, {:conditions => ['node_question_relations.node_id = ?', @node], :include => [:node_question_relations]})
        format.html { render :action => "edit" }
        format.xml  { render :xml => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.xml
  def destroy
    @node = Node.find(params[:id])
    @node.destroy
		redirect_to :action => "listByCourse" , :course_id => @node.course_id

  end


	def importFromCompendium
		render
	end

	def saveImportFromCompendium
		#todo authoriz
		file = params[:mapFile]	
		if file
			if User.find(session[:userid]).useraccount_type == User::PROF
				#Teacher account
				teacher_id = session[:useraccount_id]
			else
				#admin account
				teacher_id = Teacher.limit(1).pluck("id").first
			end

			relatedContentFiles = importCompendiumMap(file.path, teacher_id, params[:course_id])
			
			flash[:notice] = "Mapa importado"
		else
			flash[:notice] = "Error importando mapa"
		end
		flash[:notice] << "<br/>Los siguente ficheros especificados como contenidos? " if relatedContentFiles.size > 0
		relatedContentFiles.each do |fn|
			flash[:notice] << "<br/>#{fn}"
		end
		redirect_to :action => "listByCourse" , :course_id => params[:course_id]
	end

	private

	def node_params
			params.require(:node).permit(:content, :course_id, :minPassPoints, :keywords)
	end

end

app/helpers/nodes_helper.rb
require "rexml/document"
require "rexml/xpath"
#require 'iconv'

module NodesHelper

	include QuestionsHelper


	def adminNode(n)
		User.find(session[:userid]).useraccount_type == User::ADMIN || n.teacher.user.id == session[:userid] 
	end

	COMPENDIUMNODE_TYPE_MAP = 2
	COMPENDIUMNODE_TYPE_LIST = 1


	def importCompendiumMap(filename, teacher_id, course_id)
		groupnodetypes = [ COMPENDIUMNODE_TYPE_LIST, COMPENDIUMNODE_TYPE_MAP  ]
		nodesNotGroupTypeMap = Hash.new
		nodesGroupTypeList = Array.new
		viewNodesMap = Hash.new
		addFiles = Hash.new
		document =  REXML::Document.new(getUTF8encodedString(filename))

		#Nodes
		REXML::XPath.each( document, "//node") do |element|
			ActiveRecord::Base.logger.debug("element") 
			ActiveRecord::Base.logger.debug(element) 
			nodeid = element.attributes["id"]
			nodeLabel = element.attributes["label"]
			ActiveRecord::Base.logger.debug "nodeid #{nodeid}"
			ActiveRecord::Base.logger.debug "nodelabel #{nodeLabel}"
			nodeType = element.attributes["type"].to_i
			ActiveRecord::Base.logger.debug "nodetype #{nodeType}"
			if nodeType == 0
				#why 4? doc
				nodeType = 4
				ActiveRecord::Base.logger.debug "nodetype not a number set to 4"
			end
			if groupnodetypes.find{|t| t==nodeType}.nil?	
				modelNode = Node.new
				modelNode.content = nodeLabel
				modelNode.teacher_id = teacher_id
				modelNode.course_id = course_id
				modelNode.minPassPoints = 0.5
				modelNode.save
				ActiveRecord::Base.logger.debug "nodeid saved #{modelNode.id}"
				nodesNotGroupTypeMap[nodeid] = modelNode.id
				#	view if the node has an associated file
				element.elements["source"].each do |srcFileElem|
					addFiles[srcFileElem] = nodeid
					ActiveRecord::Base.logger.debug "SRCFILE #{srcFileElem}"
				end
			else
				nodesGroupTypeList.push(nodeid)
			end

		end
		#Views
		REXML::XPath.each( document, "//view") do |element| 
			viewid = element.attributes["viewref"]
			nodeid = element.attributes["noderef"]
			if (nodesNotGroupTypeMap[viewid] || nodesGroupTypeList.include?(viewid) ) && (nodesNotGroupTypeMap[nodeid] || nodesGroupTypeList.include?(nodeid) )
				viewNodesMap[viewid] = Array.new if !viewNodesMap[viewid]
				viewNodeIdsList = viewNodesMap[viewid]
				viewNodeIdsList.push(nodeid) if viewNodeIdsList.find{|id| id == nodeid}.nil?
			end
		end

		#Links
		REXML::XPath.each( document, "//link") do |element| 
			fromNodeId = element.attributes["from"]
			toNodeId = element.attributes["to"]
			edgeLabel = element.attributes["label"].to_i
			# Insert edge from a node to another node
			if nodesNotGroupTypeMap[fromNodeId] && nodesNotGroupTypeMap[toNodeId]
				srcId = nodesNotGroupTypeMap[fromNodeId]
				destId = nodesNotGroupTypeMap[toNodeId]
			
				edge = Edge.new
				edge.src_id = srcId
				edge.dest_id = destId
				edge.dep = edgeLabel
				edge.save
			# edge from a node to a map of nodes
			elsif  nodesNotGroupTypeMap[fromNodeId] && nodesGroupTypeList.include?(toNodeId)	
					if (viewNodesMap[toNodeId] )
						srcId = nodesNotGroupTypeMap[fromNodeId]
						viewNodesMap[toNodeId].each do |destIdComp| 
							destId = nodesNotGroupTypeMap[destIdComp]
							edge = Edge.new
							edge.src_id = srcId
							edge.dest_id = destId
							edge.dep = edgeLabel
							edge.save
						end
					else
						ActiveRecord::Base.logger.debug "Node of Type Map/List but it's not a View ??? #{toNodeId}"
					end	 
			# edge from a map of nodes to a node
			elsif  nodesNotGroupTypeMap[toNodeId] && nodesGroupTypeList.include?(fromNodeId)
				if (viewNodesMap[fromNodeId] )
						destId = nodesNotGroupTypeMap[toNodeId]
						viewNodesMap[fromNodeId].each do |srcIdComp| 
							srcId = nodesNotGroupTypeMap[srcIdComp]
							edge = Edge.new
							edge.src_id = srcId
							edge.dest_id = destId
							edge.dep = edgeLabel
							edge.save
						end
				else
					ActiveRecord::Base.logger.debug "Node of Type Map/List but it's not a View ??? #{fromNodeId}"
				end	 

			# edge from a map of nodes to a a map of nodes
			elsif   nodesGroupTypeList.include?(fromNodeId) && nodesGroupTypeList.include?(toNodeId)
				if (viewNodesMap[fromNodeId] && viewNodesMap[toNodeId])
				viewNodesMap[fromNodeId].each do |srcIdComp|
					viewNodesMap[toNodeId].each do |destIdComp|
						srcId = nodesNotGroupTypeMap[srcIdComp]
						destId = nodesNotGroupTypeMap[destIdComp]
						edge = Edge.new
						edge.src_id = srcId
						edge.dest_id = destId
						edge.dep = edgeLabel
						edge.save
					end
				end
				else
					ActiveRecord::Base.logger.debug "Node of Type Map/List but it's not a View ??? #{fromNodeId} or #{toNodeId}"
				end	 
			end
		end
	return addFiles
	end



	private 
		def	getUTF8encodedString(filename)
			#REXML only works with UTF8
			#tochange with ruby1.9
			#remove header use gsub with ruby1.9
			filestring = `file #{filename}`
			iconvlist = `iconv -l`.split("//\n")
			fromenc = "UTF-16"
			iconvlist.each do |enc|
				 if filestring =~  /#{enc}/
					fromenc = enc
					break
				end
			end
			ActiveRecord::Base.logger.warn("FROM ENCODING = #{fromenc}")
			#iconv deprecateed since 1.9.3
			#filecontents = Iconv.conv("UTF-8", fromenc, File.read(filename))
			ec = Encoding::Converter.new("UTF-16BE", "UTF-8")
			filecontents = ec.convert( File.read(filename))
			ActiveRecord::Base.logger.warn("FILECONTENTS ENCODING = #{filecontents.encoding.name}")
			lines = filecontents.split("\n")
			contents = ""
			lines.each do |line|
#				ActiveRecord::Base.logger.info line
#				ActiveRecord::Base.logger.info line !~ /<\?xml/
#				ActiveRecord::Base.logger.info line !~  /<!DOCTYPE/
				
				contents << line if line !~ /<\?xml/ && line !~ /<!DOCTYPE/ 
			end
			#	ActiveRecord::Base.logger.info "Contents"
			#	ActiveRecord::Base.logger.info contents
			return contents
		end

	
end

app/views/nodes/_nodesDep.html.erb
<h2><%= t('assoc_nodes') %></h2>
<% for node in @nodes %>
<p>
	<b><%= node.content %></b>:
	<%= text_field_tag "rel[#{node.id}]"   %>
  <% Work::WORK_TYPES.each do |q| %>
    <%= radio_button_tag "type[#{node.id}]" , q, (@worktype == q) %><%= t("workType#{q}") %>
  <% end %>
</p>
<% end %>

app/views/nodes/edit.html.erb
<h1><%= t('edit_node') %></h1>

<%= form_for(@node) do |f| %>
  	  <% if @node.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= t :error_update, :count => @node.errors.count %></h2>
	
	      <ul>
	      <% @node.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


  <p>
    <%= t('course') %><br />
    <%= @node.course.name %>
  </p>
  <p>
    <%= t('content') %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= t('minPassPoints') %><br />
    <%= f.text_field :minPassPoints %>
  </p>
  <p>
    <%= t 'keywords' %> <br />
    <%= f.text_field :keywords %>
  </p>
  <p>
    <%= f.submit t("update") %>
  </p>
<% end %>

<b><%= t('assoc_questions') %></b>

<div class="wice-grid-container" id="grid"><table  class="table-striped table-bordered table wice-grid">
<thead><tr  class="wice-grid-title-row">

			<th> <%= t('course') %> </th>	
			<th> <%= t('name') %> </th>	
			<th> <%= t(:edit_node_question_relation) %> </th>
			<th> <%= t(:delete_node_question_relation) %> </th>
			<th> <%= t('edit_question')  %> </th>
			<th> <%= t('dependency')  %> </th>
			
		</tr>	
    <tr>		
  </thead>
  <tbody>

 <% for question in @questions %>
<tr>
	<td>
		<%=  question.course.name %>
	</td>
	<td>
    <%=  question.content %>
	</td>

	<td>
			<%= link_to "Editar" , edit_node_question_relation_path(question.node_question_relations[0]) %>
	</td>

	<td>
    	<%= link_to t('delete'),url_for(:controller => 'node_question_relations',  :action => "destroy" , :id =>question.node_question_relations[0].id,  :from => 'nodes') ,{ :confirm => t(:deletion_node_question_relation_confirmation), :method => :delete }%>

	</td>

	<td>
		<%= 	link_to t("edit") , edit_question_path(question.id)  if adminQN(question)%>

	</td>

	<td>
         <%=   question.node_question_relations[0].dep %>

	</td>
     </tr>       
 <% end %>


  </tbody>
</table>

<%= will_paginate @questions %>

</div>





<%= link_to t('node_question_relation_new_question'), :controller => "node_question_relations" , :action => "newQuestion" , :node_id => @node.id %>
<br/>
<%= link_to t('node_question_relation_add_questions_from_node'), :controller => "node_question_relations" , :action => "newQuestionsFromNode" , :node_id => @node.id %>

<br />
<b><%= t('node_succ_list') %></b>
<table>
<tr>
	<th><%= t('content') %></th>
	<th><%= t('dependency') %></th>
	<th><%= t('edit') %></th>
	<th><%= t('delete') %></th>
</tr>


<% @node.edges_as_source.each do |e| %>
<% n = e.dest %>
  <tr>
    <td><%=h n.content %></td>
    <td><%=h e.dep %></td>
    <td><%= link_to t('edit'), :controller => 'edges' , :action => "edit" , :src_id => e.src_id, :dest_id => e.dest_id %></td>
    <td><%= link_to t('delete'),url_for(:controller => 'edges',  :action => "destroy" , :src_id => e.src_id, :dest_id => e.dest_id) ,{ :confirm => 'Estas seguro que quieres borrar el succesor del nodo?', :method => :delete } %></td>
  </tr>
<% end %>
</table>
<%= link_to t('new_edge_dest'), :controller => "edges" , :action => "new_src" , :src_id => @node.id %>

<br />

<b><%= t('node_pred_list') %></b>
<table>

<tr>
	<th><%= t('content') %></th>
	<th><%= t('dependency') %></th>
	<th><%= t('edit') %></th>
	<th><%= t('delete') %></th>
</tr>
<% @node.edges_as_dest.each do |e| %>
<% n = e.src %>

  <tr>
    <td><%=h n.content %></td>
    <td><%=h e.dep %></td>
    <td><%= link_to t('edit'), :controller => 'edges' , :action => "edit" , :src_id => e.src_id, :dest_id => e.dest_id %></td>
    <td><%= link_to t('delete'),url_for(:controller => 'edges',  :action => "destroy" , :src_id => e.src_id, :dest_id => e.dest_id) ,{ :confirm => 'Estas seguro que quieres borrar el predecesor del nodo?', :method => :delete } %></td>
  </tr>
<% end %>
</table>
<%= link_to t('new_edge_src'), :controller => "edges" , :action => "new_dest" , :dest_id => @node.id %>
<br />

<b><%= t('node_related_content_list') %></b>
<table>

<tr>
	<th><%= t('filename') %></th>
	<th><%= t('description') %></th>
	<th><%= t('view') %></th>
	<th><%= t('edit') %></th>
	<th><%= t('delete') %></th>
</tr>
<% @node.related_contents.each do |n| %>

  <tr>
    <td><%=h n.filename %></td>
    <td><%=h n.description %></td>
    <td><%= link_to t('view'), n %></td>
    <td><%= link_to t('edit'), edit_related_content_path(n) %></td>
    <td><%= link_to t('delete'), n, :confirm => t('deletion_confirmation'), :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to t('node_new_related_content'), :controller => "related_contents" , :action => "new" , :node_id => @node.id %>


<br />
<%= link_to t('view'), @node %> |
<%= link_to t('back'), :action => "listByCourse" , :course_id => @node.course_id %>

app/views/nodes/importFromCompendium.html.erb
<h1><%= t('import_compendium_map') %></h1>



<%= form_tag({:controller => 'nodes' , :action => 'saveImportFromCompendium'  }, {:method => :post , :multipart => true}) do |f| %>
	<%= hidden_field_tag :course_id , params[:course_id] %>
  <p>
    <%= t('upload_file') %><br />
    <%= file_field_tag :mapFile %>
  </p>
  <p>
    <%= submit_tag t('import') %>
  </p>
<% end %>

app/views/nodes/new.html.erb
<h1><%= t('course_new_node')  %></h1>
<%= form_for(@node) do |f| %>
  	  <% if @node.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= t :error_save, :count => @node.errors.count %></h2>
	      <ul>
	      <% @node.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


    <%= f.hidden_field :course_id %>
  <p>
   <%= t :content %> <br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= t 'minPassPoints' %> <br />
    <%= f.text_field :minPassPoints %>
  </p>
  <p>
    <%= t 'keywords' %> <br />
    <%= f.text_field :keywords %>
  </p>
  <p>
    <%= f.submit t("create") %>
  </p>
<% end %>

<%= link_to t('back'), @node.course %>