config/routes.rb
SienaCsl::Application.routes.draw do





#http verbs are:
#get, post(create new item), put(replace existing item), patch(update existing item), delete(delete existing item)
#patch default for forms hidden field _method


def makeRoutes
	mount ActionCable.server => '/cable'

  resources :fuzzy_rules
  resources :chat_messages
  resources :proposed_keywords

  resources :competence_nodes

  resources :student_alu_groups

  resources :alu_groups

  resources :competence_groups

  resources :competences

  resources :related_contents

  resources :tests

  resources :answers

  resources :question_responses

  resources :node_question_relations

  resources :edges

  resources :teacher_assigns

  resources :student_assigns
  resources :grouptest_chatmessages

  resources :teachers

  resources :admins

  resources :students

  resources :courses
  resources :stopwords

  resources :works

  resources :nodes

  resources :questions

  resources :users

  get '/' => "users#getUserHome" 


  get 'login'  => 'users#login', :as => :login
  get 'logout'  => 'users#logout', :as => :logout
  get 'register'  => 'users#new', :as => :register
  get 'lost_password'  => 'users#get_lost_password', :as => :lost_password

	get 'cambiarEstado/:userid' => 'users#changeActive'
	get 'entrarComo/:userid' => 'users#loginAs'
	get 'home' => 'users#getUserHome'
	get 'ayuda' => 'users#help'
	get 'matricular_alumno/:course_id' => 'student_assigns#enroll'
	get 'matricular_profesor/:course_id' => 'teacher_assigns#enroll'
	get 'cambiar_coordinador/:id/:course_id' => 'teacher_assigns#changeCoordinator'
	get 'matricular_profesor_admin/:course_id/:teacher_id' => 'teacher_assigns#assign_to_course'
	post 'matricular_alumnos/:course_id' => 'student_assigns#register_to_course'
	get 'matricular_profesores/:course_id' => 'teacher_assigns#register_to_course'
	get 'nuevo_nodo/:course_id' => 'nodes#new'
	get 'nuevo_comp_grupo/:competence_id' => 'competence_groups#newAluGroup'
	get 'nuevo_comp_nodo/:competence_id' => 'competence_nodes#newNode'
	get 'importar_compendium/:course_id' => 'nodes#importFromCompendium'
	get 'nueva_pregunta/:course_id' => 'questions#new'
	get 'borrar_imagen/:question_id' => 'questions#deleteImgFile'
 get 'nueva_respuesta/:question_id' => 'question_responses#new'
 get 'nuevo_nodo_asoc/:question_id' => 'node_question_relations#newNode'
 get 'nueva_pregunta_asoc/:node_id' => 'node_question_relations#newQuestion'
 get 'nuevas_preguntas_delnodo/:node_id' => 'node_question_relations#newQuestionsFromNode'
 get 'nuevo_alumno/:alu_group_id' => 'student_alu_groups#newStudent'
 get 'trabajos_asignatura/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourse'
 get 'trabajos_asignatura_xml/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourseXML'
 get 'trabajos/:student_id/course_id' => 'works#listByStudent'
 get 'nuevo_trabajo/:student_id/:course_id' => 'works#new'
 get 'nodos/:course_id' => 'nodes#listByCourse' 
 get 'preguntas/:course_id' => 'questions#listByCourse' 
 get 'createIndex/:question_id' => 'questions#createIndexDbPedia' 
 get 'deleteIndex/:question_id' => 'questions#deleteIndexDbPedia' 
 get 'profesores/:course_id' => 'teacher_assigns#listByCourse' 
 get 'alumnos/:course_id' => 'student_assigns#listByCourse' 
 get 'grupos/:course_id' => 'alu_groups#listByCourse' 
 get 'profesores_no_matriculados/:course_id' => 'teacher_assigns#listByCourseNot' 
 get 'alumnos_no_matriculados/:course_id' => 'student_assigns#listByCourseNot' 
 get 'nuevo_grupo/:course_id' => 'alu_groups#new' 
 get 'grupos_de_alumnos/:student_id/:course_id' => 'alu_groups#listByStudentAndCourse' 
 get 'nuevo_predecesor/:dest_id' => 'edges#new_dest'
 get 'nuevo_sucesor/:src_id' => 'edges#new_src'
 get 'editar/:src_id/:dst_id' => 'edges#edit'
 get 'borrar/:src_id/:dst_id' => 'edges#destroy'
 get 'nuevo_contenido/:node_id' => 'related_contents#new'
 get 'html_related/:related_content_id/*filename' => 'related_contents#view_as_html'  , :filename => /.+/
 get 'asignaturas_mat' => 'courses#indexAssigned'
 get 'alumnos_en/:course_id' => 'courses#allStudents'
 get 'exportar_asignatura/:course_id' => 'courses#export'
	get 'importar_asignatura' => 'courses#import'
 get 'cambiar_tema/:theme' => 'users#changeTheme'
 get 'cambiar_idioma/:locale' => 'users#set_locale'
 get 'competencias_grupo/:alu_group_id' => 'competences#listByGroup'
 get 'competencias_grupos' => 'competences#listByGroups'
 get 'ver_chats/:username' => 'users#listChats'
 post 'ver_pregunta_alu/:question_id/:test_id' => 'questions#showAlu'

 get 'changePassword/:userid' => 'users#chPw' 
 get 'usuarios_no_activos' => 'users#indexNotActive'
 get 'nuevo_test/:work_id' => 'questions#starttest'
 get 'borrar_image_test/:test_id' => 'tests#deleteTestImage'
 get 'nuevo_trabajo_asign/:course_id/:assignedtoType' => 'works#newAll'

 get 'test/:test_id' => 'questions#test'
 patch 'contestar' => 'questions#answer'
 get 'regenerar_test_alumno/:test_id' => 'questions#regenerate_student_id'
 get 'register_to_test/:test_id' => 'tests#register_to_test'
 get 'leave_test/:test_id' => 'tests#leave_test'
 get 'cambiar_comentario/:grouptest_chatmessage_id' => 'grouptest_chatmessages#changeComment'

 get 'lista_tests/:work_id' => 'tests#listByWork'
 get 'test_xml/:test_id' => 'tests#showXML'	

 get 'subir_fichero_contenido/:related_content_id' => 'related_contents#uploadFile'
 get 'borrar_fichero_contenido/:name/:related_content_id' => 'related_contents#deleteFile'
 get 'fichero_principal_contenido/:name/:related_content_id' => 'related_contents#mainFile'
 get 'lista_contenidos/:node_id/:recover' => 'related_contents#listByNodeAndRecover'
 get 'subir_fichero_competencia/:alu_group_id/:competence_id' => 'competence_groups#uploadFile'


	#proposed keywords
	 post 'ver_keyword/:question_id/:keyword' => 'proposed_keywords#show'
	 post 'keywords_para/:question_id' => 'proposed_keywords#list'
	 post 'aceptar_keyword/:question_id/:keyword' => 'proposed_keywords#accept'
	 post 'rechazar_keyword/:question_id/:keyword' => 'proposed_keywords#reject'
	 post 'rechazar_keyword/:question_id/:keyword' => 'proposed_keywords#setnew'
	 post 'stopword_keyword/:keyword' => 'proposed_keywords#setStopword'


 get ':controller(/:action(/:id(.:format)))'
 post ':controller(/:action(/:id(.:format)))'

end

makeRoutes

#scope  '/siena2' do
#	makeRoutes
#end


end

app/helpers/courses_helper.rb
module CoursesHelper
include ActiveSupport::Inflector

MAPIMAGES = "mapImages" unless const_defined?(:MAPIMAGES)
MAPIMAGESDIR = "#{Rails.root.to_s}/public/#{MAPIMAGES}" unless const_defined?(:MAPIMAGESDIR)


def generatePng(c)
	t = "digraph G {\n"
	c.nodes.each do |n|
		t << n.id.to_s
		t << "[label=\""
		i = 0
		a = n.content.gsub(/\s+/) do |space|
			i = i + 1	
			if i == 3
				i = 0
					 '\n'
			else
						 " "	
	 		end
		end
		t << a
		t << "\"]\n"
	end
	c.nodes.each do |n|
		n.edges_as_source.each do |s|
			t << n.id.to_s
			t << " -> "
			t << s.dest_id.to_s
			t << "\n"
		end
	end
	t<<"}\n"
	fn = "#{MAPIMAGESDIR}/#{c.id}"
  f = File.open(fn + ".dot" , 'w')
  f.write(t)
  f.close
	`dot -Tpng  #{fn}.dot -o #{fn}.png`
end


def importFromXML(file)
	doc = REXML::Document.new file.read()
	#msg = ""
	begin
		if Course.find_by_name(doc.root.elements["name"].text)
			course = Course.create(:name => (doc.root.elements["name"].text + Time.new.to_i.to_s)  ) 
			#msg << "course #{doc.root.elements["name"].text} exists \n"
		else
			course = Course.create(:name =>  doc.root.elements["name"].text)
			#msg << "course #{doc.root.elements["name"].text} created \n"
		end
		usermap = Hash.new
		studentmap = Hash.new
		teachermap = Hash.new
		nodemap = Hash.new
		alugroupmap = Hash.new
		#teachers
		doc.elements.each("course/teachers/teacher")  do |ta|
			u = ta.elements["user"] 
			user = User.find_by_username(u.elements["username"].text)
			if user.nil?
				user = User.new(:username => u.elements["username"].text , :email => u.elements["email"].text, :useraccount_type => User::PROF, :name => u.elements["name"].text)
				#these are not amss assigned: password_hash, useraccount_id, active, password_salt
				user.password_hash=u.elements["password_hash"].text
				user.password_salt=u.elements["password_salt"].text
				user.active = u.elements["active"].text
				teacher = Teacher.create
				user.useraccount_id =  teacher.id
				user.save
				#msg << "prof  #{user.username} created\n"
			elsif user.useraccount_type == User::PROF
				teacher = user.useraccount
				#msg << "teacher #{teacher.id} inserted in course\n"
			else
				ActiveRecord::Base.logger.warn("!!!WARNING!!!want to insert teacher, but a user with username = #{u.elements["username"].text} with type #{user.useraccount_type} already exists")
			end	
			usermap[u.elements["id"].text] = user.id
			if teacher
				TeacherAssign.create(:teacher_id => teacher.id, :course_id => course.id )
				teachermap[ta.elements["id"].text] = teacher.id
			end
		end

		if teachermap.size > 0
			defaultteacherid = teachermap.first[1]
		else
			ActiveRecord::Base.logger.warn("no teacher matr")
			defaultteacherid = nil
		end

		#students
		doc.elements.each("course/students/student")  do |sa|
			u = sa.elements["user"] 
			user = User.find_by_username(u.elements["username"].text)

			if user.nil?
				user = User.new(:username => u.elements["username"].text , :email => u.elements["email"].text, :useraccount_type => User::ALU, :name => u.elements["name"].text)
				#these are not amss assigned: password_hash, useraccount_id, active, password_salt
				user.password_hash=u.elements["password_hash"].text
				user.password_salt=u.elements["password_salt"].text
				user.active = u.elements["active"].text
				student = Student.create
				user.useraccount_id =  student.id
				user.save
				#msg << "prof  #{user.username} created\n"
			elsif user.useraccount_type == User::ALU
				student = user.useraccount
				#msg << "student #{student.id} inserted in course\n"
			else
				ActiveRecord::Base.logger.warn("!!!WARNING!!!want to insert student, but a user with username = #{u.elements["username"].text} with type #{user.useraccount_type} already exists")
			end	
			usermap[u.elements["id"].text] = user.id
			if student
				StudentAssign.create(:student_id => student.id, :course_id => course.id )
				studentmap[sa.elements["id"].text] = student.id
			end
		end
		if studentmap.size > 0
			defaultstudentid = studentmap.first[1]
		else
			ActiveRecord::Base.logger.warn("no student matr")
			defaultstudentid = nil
		end



		#alu_groups
		doc.elements.each("course/alu_groups/alu_group")  do |sa|
				alu_group = AluGroup.create(:name => sa.elements["name"].text, :course_id => course.id)
				alugroupmap[sa.elements["id"].text] = alu_group.id
				tlist = sa.elements.each("students/student") do |t|
					sid = t.elements["id"].text.to_i 
					if (sid_from_map = studentmap[sid])
						StudentAluGroup.create_by_student_id_and_alu_group_id(sid_from_map, alu_group.id)
					end
	
				end
		end	
		#nodes and works
		doc.elements.each("course/nodes/node")  do |ne|
			content = ne.elements["content"].text
			if !(teacher_id = teachermap[ne.elements["teacher_id"].text])
				teacher_id = defaultteacherid
				ActiveRecord::Base.logger.warn("add node teacher not  matr using default")
			end
			if teacher_id	
				#msg << "create node: teacher_id #{ne.elements["teacher_id"].text} not in map set to null\n"
				node = Node.new(:content => content, :course_id => course.id, :minPassPoints => ne.elements["minPassPoints"].text )
				node.teacher_id = teacher_id
				node.save
			end
				#msg << "node #{content} created\n"
			if node
				nodemap[ne.elements["id"].text] = node.id
				#works
				ne.elements["works"].elements.each("work") do |we|
					assignedto_type = we.elements["assignedto_type"].text
					if assignedto_type == 'Student'
					#assigned to student
						assignedto_id = studentmap[we.elements["assignedto_id"].text]
						assignedto_id = defaultstudentid if assignedto_id.nil?
					else
						#assigned to alu_group
						assignedto_id = alugroupmap[we.elements["assignedto_id"].text]
					end
	
					if assignedto_id.nil?
						#msg << "student_id #{we.elements['student_id'].text} not in map(desmatr) work will not be inserted\n"
					else
						Work.create(:node_id => node.id ,:assignedto_type => assignedto_type, :assignedto_id => assignedto_id , :initialpoints => we.elements["initialpoints"].text, :worktype => we.elements["worktype"].text)
					end
				end
			end
			#end works
		end
		#questions and node_question_relations
		doc.elements.each("course/questions")  do |qes|
			qes.elements.each("question") do |qe|
				content = qe.elements["content"].text
				if !(teacher_id = teachermap[qe.elements["teacher_id"].text])
					teacher_id = defaultteacherid
					ActiveRecord::Base.logger.warn("add question teacher not  matr using default")
				end
				if teacher_id	
					question = Question.new(:content => content, :course_id => course.id , :answerTime => qe.elements["answerTime"].text , :correctAnswer => qe.elements["correctAnswer"].text , :difficulty => qe.elements["difficulty"].text , :img => qe.elements["img"].text , :luck => qe.elements["luck"].text )
					question.teacher_id = teacher_id
					question.save
				else
					ActiveRecord::Base.logger.warn("!!!WARNING!!! teacher with #{qe.elements["teacher_id"].text} not matriculated in original course")
				end
					#msg << "question #{content} created\n"
				if question
					#nqr
					qe.elements["node_question_relations"].elements.each("node_question_relation") do |nqre|
						node_id = nodemap[nqre.elements["node_id"].text]
						if node_id.nil?
							#msg << "node_id #{nqre.elements['node_id'].text} not in map\n"
						else
							NodeQuestionRelation.create(:node_id => node_id , :question_id => question.id , :dep => nqre.elements["dep"].text)
							#msg << "NodeQuestionRelation for node_id #{node_id} and question_id #{question.id} -  created\n"
						end
					end
					#quest_resp
					qe.elements["question_responses"].elements.each("question_response") do |qre|
						qrtext = qre.elements["response"].text
						QuestionResponse.create(:response => qrtext , :question_id => question.id )
							#msg << "QuestionResponse #{qrtext} for question_id #{question.id} created\n"
							#msg << "QuestionResponse #{qrtext} question_id #{question.id} -  exists, not inserted\n"
					end
				end
			end
			return course.name
		end
	rescue Exception => e
		ActiveRecord::Base.logger.warn "Error import xml"
		ActiveRecord::Base.logger.warn e
		ActiveRecord::Base.logger.warn e.backtrace.join("\n")
		return false
	end
	#ActiveRecord::Base.logger.warn "*************************************IMPORTXML**************************************************"
	#ActiveRecord::Base.logger.warn #msg

end

end

app/views/courses/allStudents.html.erb
<script>
  $(function() {
    $("#accordion").accordion({
        collapsible:true,
        active:false
    });
    var icons = $( "#accordion" ).accordion( "option", "icons" );
    $('.open').click(function () {
        $('.ui-accordion-header').removeClass('ui-corner-all').addClass('ui-accordion-header-active ui-state-active ui-corner-top').attr({
            'aria-selected': 'true',
            'tabindex': '0'
        });
        $('.ui-accordion-header-icon').removeClass(icons.header).addClass(icons.headerSelected);
        $('.ui-accordion-content').addClass('ui-accordion-content-active').attr({
            'aria-expanded': 'true',
            'aria-hidden': 'false'
        }).show();
    });
    $('.close').click(function () {
        $('.ui-accordion-header').removeClass('ui-accordion-header-active ui-state-active ui-corner-top').addClass('ui-corner-all').attr({
            'aria-selected': 'false',
            'tabindex': '-1'
        });
        $('.ui-accordion-header-icon').removeClass(icons.headerSelected).addClass(icons.header);
        $('.ui-accordion-content').removeClass('ui-accordion-content-active').attr({
            'aria-expanded': 'false',
            'aria-hidden': 'true'
        }).hide();
    });

  });
  </script>


Notas de todos los alumnos. En paréntesis se muestra número de preguntas con respuesta incorrecta / número total de preguntas
; nota1, nota2, nota3, nota4 | nota total si se ha rellenado por el profeosr nota4 (la calidad de los mensajes)

<div class="accordion-expand-holder">
    <button type="button" class="open">Expand all</button>
    <button type="button" class="close">Collapse all</button>
</div>

<div id="accordion">
		<% @students.each do |s| %>

    <h3><%= s.user.name %> (<%= s.user.username %>)</h3>
    <div>
			<% tests = getStudentTests(s, params[:course_id]) %>
			<% if tests[:students].size > 0 %>
				<h4> Individuales </h4>
				<% tests[:students].each do |t| %>	
					<b> <%= t[:node] %>: </b>
						<% t[:tests].each do |t| %>
							<%= t[:points] %> (<%= t[:answ] %>)
						<% end %>
				<br/>
				<% end %>
			<% end %>
			<% if tests[:alu_groups].size > 0 %>
				<h4> En grupo </h4>
				<% if tests[:gradeFromTag]!=0 %>
					<p><b><%= t('grade_total') %></b>:
					<%= "%1.3f" % tests[:gradeFromTag] %>
					</p>
				<% end %>
				<% tests[:alu_groups].each do |t| %>
					<b> <%= t[:node] %>: </b>
						<% t[:tests].each do |t| %>
							<%= t[:points] %> (<%= t[:answ] %><%= " ;#{t[:tag].grade1}, #{t[:tag].grade2}, #{t[:tag].grade3}, #{t[:tag].grade4} | #{t[:tag].grade_total}" if t.has_key?(:tag) %>)
						<% end %>

				</br>
				<% end %>
			<% end %>
		</div>
		<% end %>


</div>

app/views/courses/edit.html.erb
<h1><%= t 'edit_course' %></h1>

<%= form_for(@course) do |f| %>
  	  <% if @course.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_update, :count => @course.errors.count %></h2>	
	      <ul>
	      <% @course.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


  <p>
    <%= t :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit t(:update) %>
  </p>
<% end %>

<%= link_to t(:update), @course %> |
<%= link_to t(:back), courses_path %>

app/views/courses/import.html.erb
<h1><%= t('import_xml') %></h1>



<%= form_tag({:action => 'saveImport'  }, {:method => :post , :multipart => true}) do |f| %>
  <p>
    <%= t(:upload_file) %><br />
    <%= file_field_tag :xmlFile %>
  </p>
  <p>
    <%= submit_tag t('import') %>
  </p>
<% end %>

app/views/courses/index.html.erb
<h1><%= t :course_list %></h1>

<div class="wice-grid-container" id="grid"><table  class="table-striped table-bordered table wice-grid">
<thead><tr  class="wice-grid-title-row">
			<th> <%= t('name') %> </th>	
			<th> <%= t('view') %> </th>	
				<% if User.find(session[:userid]).useraccount_type == User::ADMIN  %>
			<th>
					<%= t('edit') %> 
			</th>
			<th>
					<%= t('delete') %> 
			</th>
		<% elsif User.find(session[:userid]).useraccount_type == User::ALU or User.find(session[:userid]).useraccount_type == User::PROF  %>
			<th>
					<%= t('state') %> 
			</th>
		<% end %>
		

		</tr>	
    <tr>		
		<%= form_tag(courses_path, method: :get) do %>
   		<th><%= text_field_tag :name, params[:name] %></th>
   		<th>&nbsp;</th>
		<% if User.find(session[:userid]).useraccount_type == User::ADMIN  %>
   		<th>&nbsp;</th>
   		<th>&nbsp;</th>
		<% elsif User.find(session[:userid]).useraccount_type == User::ALU or User.find(session[:userid]).useraccount_type == User::PROF  %>
   		<th>&nbsp;</th>
		<% end %>
   		<th class="submit" ><%= submit_tag 'Search', name: nil%></th>
		<% end %>
		</tr>

  </thead>
  <tbody>


 <% for c in @courses %>
    <tr>
	<td><%=   c.name %> </td>

	<td><%= link_to t('view'), c  if User.find(session[:userid]).useraccount_type == User::ADMIN ||  ((User.find(session[:userid]).useraccount_type == User::ALU || User.find(session[:userid]).useraccount_type == User::PROF ) && (eval("#{User.find(session[:userid]).useraccount_type}Assign.find_by_#{underscore(User.find(session[:userid]).useraccount_type)}_id_and_course_id(session[:useraccount_id] , c.id)" )))
 %> </td>
	<%	if User.find(session[:userid]).useraccount_type == User::ADMIN  %>
		<td><%= link_to t('edit'), edit_course_path(c)  %> </td>
		<td><%= link_to t('delete'), c, :confirm => t('deletion_confirmation'), :method => :delete %> </td>
	<% elsif User.find(session[:userid]).useraccount_type == User::ALU or User.find(session[:userid]).useraccount_type == User::PROF %>
	
		 <% s = eval("#{User.find(session[:userid]).useraccount_type}Assign.find_by_#{underscore(User.find(session[:userid]).useraccount_type)}_id_and_course_id(session[:useraccount_id] , c.id)") %>
		<td><%= s ? (link_to t('delete_from_course'), s, :confirm => 'Are you sure?', :method => :delete) : (link_to t('add_to_course'), :controller => "#{underscore(User.find(session[:userid]).useraccount_type)}_assigns" , :action => 'enroll' , :course_id => c.id)  %> </td>
	<%end %> 
     </tr>       
		<% end %>


  </tbody>
</table>

<%= will_paginate @courses %>

</div>







<br />

<% if User.find(session[:userid]).useraccount_type == User::ADMIN %>
	<%= link_to t('new_course'), new_course_path %>
	<br/><%= link_to t('import_xml'), :action => :import %>
<% else %>
	<%= link_to t('enrolled_courses'), :action => 'indexAssigned' %>
<% end %>

app/views/courses/indexAssigned.html.erb
<h1><%= t('course_list_assigned') %></h1>

<div class="wice-grid-container" id="grid"><table  class="table-striped table-bordered table wice-grid">
<thead><tr  class="wice-grid-title-row">
			<th> <%= t('name') %> </th>	
			<th> <%= t('view') %> </th>	
			<th> <%= t('state') %> </th>	

		</tr>	
    <tr>		
		<%= form_tag({}, method: :get) do %>
   		<th><%= text_field_tag :name, params[:name] %></th>
   		<th>&nbsp;</th>
   		<th>&nbsp;</th>
   		<th class="submit" ><%= submit_tag 'Search', name: nil%></th>
		<% end %>
		</tr>

  </thead>
  <tbody>


 <% for c in @courses %>
    <tr>
	<td><%=   c.name %> </td>
	<td><%=   link_to t('view'), c  %> </td>
	<td><%=  link_to t('delete_from_course'), eval("#{User.find(session[:userid]).useraccount_type}Assign.find_by_#{underscore(User.find(session[:userid]).useraccount_type)}_id_and_course_id(session[:useraccount_id] , c.id)"), :confirm => t('deletion_confirmation'), :method => :delete  %> </td>

     </tr>       
		<% end %>
  </tbody>
</table>

<%= will_paginate @courses %>

</div>

app/views/courses/new.html.erb
<h1><%= t('new_course') %></h1>

<%= form_for(@course) do |f| %>
  	  <% if @course.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_save, :count => @course.errors.count %></h2>	
	      <ul>
	      <% @course.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


  <p>
    <%= t :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit t(:crear) %>
  </p>
<% end %>

<%= link_to t(:back), courses_path %>

app/views/courses/show.html.erb
<p>
  <b><%= t(:name) %>:</b>
  <%=h @course.name %>
</p>

<% if User.find(session[:userid]).useraccount_type == User::ADMIN %>
	<%= link_to t('alu_group_list', :coursename => @course.name), :controller => "alu_groups" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('student_assign_list', :coursename => @course.name), :controller => "student_assigns" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('teacher_assign_list', :coursename => @course.name), :controller => "teacher_assigns" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('course_node_list'), :controller => "nodes" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('course_question_list'), :controller => "questions" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('export_xml'), :action => "export" , :course_id => @course.id %> <br/>
	<% if @hasPng %>
		<a href="<%= "/mapImages/#{@course.id}.png" %>"><%= t('course_image') %></a> |
	<% end %>
	<%= link_to t('generate_image') , :action => "createPng" , :id => @course.id %> <br/>
	<%= link_to t('edit'), edit_course_path(@course) %> <br/>
<% end %>

<% if User.find(session[:userid]).useraccount_type == User::PROF %>

<% if TeacherAssign.find_by_teacher_id_and_course_id(session[:useraccount_id] , @course.id).coordinator? %>
	<p><b> Coordinador </b></p>
<% end %>

	<%= link_to t('alu_group_list', :coursename => @course.name), :controller => "alu_groups" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('student_assign_list', :coursename => @course.name), :controller => "student_assigns" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('course_node_list'), :controller => "nodes" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<%= link_to t('course_question_list'), :controller => "questions" , :action => "listByCourse" , :course_id => @course.id %> <br/>
	<% if @hasPng %>
		<a href="<%= "/mapImages/#{@course.id}.png" %>"><%= t('course_image') %></a> |
	<% end %>
	<%= link_to t('generate_image') , :action => "createPng" , :id => @course.id %> <br/>


<% end %>

<% if User.find(session[:userid]).useraccount_type == User::ALU %>
	<%= link_to t('work_list'), :controller => "works" , :action => "listByAssignedtoAndCourse" , :assignedto_id =>session[:useraccount_id] ,:course_id => @course.id, :assignedto_type => 'Student' %> <br/>
	<%= link_to t('alu_group_list'), :controller => "alu_groups" , :action => "listByStudentAndCourse" , :student_id => session[:useraccount_id] ,:course_id => @course.id %> <br/>
<% end %>


<%= link_to t('course_list'), courses_path %>