config/routes.rb
SienaCsl::Application.routes.draw do





#http verbs are:
#get, post(create new item), put(replace existing item), patch(update existing item), delete(delete existing item)
#patch default for forms hidden field _method


def makeRoutes
	mount ActionCable.server => '/cable'

  resources :fuzzy_rules
  resources :chat_messages
  resources :proposed_keywords

  resources :competence_nodes

  resources :student_alu_groups

  resources :alu_groups

  resources :competence_groups

  resources :competences

  resources :related_contents

  resources :tests

  resources :answers

  resources :question_responses

  resources :node_question_relations

  resources :edges

  resources :teacher_assigns

  resources :student_assigns
  resources :grouptest_chatmessages

  resources :teachers

  resources :admins

  resources :students

  resources :courses
  resources :stopwords

  resources :works

  resources :nodes

  resources :questions

  resources :users

  get '/' => "users#getUserHome" 


  get 'login'  => 'users#login', :as => :login
  get 'logout'  => 'users#logout', :as => :logout
  get 'register'  => 'users#new', :as => :register
  get 'lost_password'  => 'users#get_lost_password', :as => :lost_password

	get 'cambiarEstado/:userid' => 'users#changeActive'
	get 'entrarComo/:userid' => 'users#loginAs'
	get 'home' => 'users#getUserHome'
	get 'ayuda' => 'users#help'
	get 'matricular_alumno/:course_id' => 'student_assigns#enroll'
	get 'matricular_profesor/:course_id' => 'teacher_assigns#enroll'
	get 'cambiar_coordinador/:id/:course_id' => 'teacher_assigns#changeCoordinator'
	get 'matricular_profesor_admin/:course_id/:teacher_id' => 'teacher_assigns#assign_to_course'
	post 'matricular_alumnos/:course_id' => 'student_assigns#register_to_course'
	get 'matricular_profesores/:course_id' => 'teacher_assigns#register_to_course'
	get 'nuevo_nodo/:course_id' => 'nodes#new'
	get 'nuevo_comp_grupo/:competence_id' => 'competence_groups#newAluGroup'
	get 'nuevo_comp_nodo/:competence_id' => 'competence_nodes#newNode'
	get 'importar_compendium/:course_id' => 'nodes#importFromCompendium'
	get 'nueva_pregunta/:course_id' => 'questions#new'
	get 'borrar_imagen/:question_id' => 'questions#deleteImgFile'
 get 'nueva_respuesta/:question_id' => 'question_responses#new'
 get 'nuevo_nodo_asoc/:question_id' => 'node_question_relations#newNode'
 get 'nueva_pregunta_asoc/:node_id' => 'node_question_relations#newQuestion'
 get 'nuevas_preguntas_delnodo/:node_id' => 'node_question_relations#newQuestionsFromNode'
 get 'nuevo_alumno/:alu_group_id' => 'student_alu_groups#newStudent'
 get 'trabajos_asignatura/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourse'
 get 'trabajos_asignatura_xml/:assignedto_type/:assignedto_id/:course_id' => 'works#listByAssignedtoAndCourseXML'
 get 'trabajos/:student_id/course_id' => 'works#listByStudent'
 get 'nuevo_trabajo/:student_id/:course_id' => 'works#new'
 get 'nodos/:course_id' => 'nodes#listByCourse' 
 get 'preguntas/:course_id' => 'questions#listByCourse' 
 get 'createIndex/:question_id' => 'questions#createIndexDbPedia' 
 get 'deleteIndex/:question_id' => 'questions#deleteIndexDbPedia' 
 get 'profesores/:course_id' => 'teacher_assigns#listByCourse' 
 get 'alumnos/:course_id' => 'student_assigns#listByCourse' 
 get 'grupos/:course_id' => 'alu_groups#listByCourse' 
 get 'profesores_no_matriculados/:course_id' => 'teacher_assigns#listByCourseNot' 
 get 'alumnos_no_matriculados/:course_id' => 'student_assigns#listByCourseNot' 
 get 'nuevo_grupo/:course_id' => 'alu_groups#new' 
 get 'grupos_de_alumnos/:student_id/:course_id' => 'alu_groups#listByStudentAndCourse' 
 get 'nuevo_predecesor/:dest_id' => 'edges#new_dest'
 get 'nuevo_sucesor/:src_id' => 'edges#new_src'
 get 'editar/:src_id/:dst_id' => 'edges#edit'
 get 'borrar/:src_id/:dst_id' => 'edges#destroy'
 get 'nuevo_contenido/:node_id' => 'related_contents#new'
 get 'html_related/:related_content_id/*filename' => 'related_contents#view_as_html'  , :filename => /.+/
 get 'asignaturas_mat' => 'courses#indexAssigned'
 get 'alumnos_en/:course_id' => 'courses#allStudents'
 get 'exportar_asignatura/:course_id' => 'courses#export'
	get 'importar_asignatura' => 'courses#import'
 get 'cambiar_tema/:theme' => 'users#changeTheme'
 get 'cambiar_idioma/:locale' => 'users#set_locale'
 get 'competencias_grupo/:alu_group_id' => 'competences#listByGroup'
 get 'competencias_grupos' => 'competences#listByGroups'
 get 'ver_chats/:username' => 'users#listChats'
 post 'ver_pregunta_alu/:question_id/:test_id' => 'questions#showAlu'

 get 'changePassword/:userid' => 'users#chPw' 
 get 'usuarios_no_activos' => 'users#indexNotActive'
 get 'nuevo_test/:work_id' => 'questions#starttest'
 get 'borrar_image_test/:test_id' => 'tests#deleteTestImage'
 get 'nuevo_trabajo_asign/:course_id/:assignedtoType' => 'works#newAll'

 get 'test/:test_id' => 'questions#test'
 patch 'contestar' => 'questions#answer'
 get 'regenerar_test_alumno/:test_id' => 'questions#regenerate_student_id'
 get 'register_to_test/:test_id' => 'tests#register_to_test'
 get 'leave_test/:test_id' => 'tests#leave_test'
 get 'cambiar_comentario/:grouptest_chatmessage_id' => 'grouptest_chatmessages#changeComment'

 get 'lista_tests/:work_id' => 'tests#listByWork'
 get 'test_xml/:test_id' => 'tests#showXML'	

 get 'subir_fichero_contenido/:related_content_id' => 'related_contents#uploadFile'
 get 'borrar_fichero_contenido/:name/:related_content_id' => 'related_contents#deleteFile'
 get 'fichero_principal_contenido/:name/:related_content_id' => 'related_contents#mainFile'
 get 'lista_contenidos/:node_id/:recover' => 'related_contents#listByNodeAndRecover'
 get 'subir_fichero_competencia/:alu_group_id/:competence_id' => 'competence_groups#uploadFile'


	#proposed keywords
	 post 'ver_keyword/:question_id/:keyword' => 'proposed_keywords#show'
	 post 'keywords_para/:question_id' => 'proposed_keywords#list'
	 post 'aceptar_keyword/:question_id/:keyword' => 'proposed_keywords#accept'
	 post 'rechazar_keyword/:question_id/:keyword' => 'proposed_keywords#reject'
	 post 'rechazar_keyword/:question_id/:keyword' => 'proposed_keywords#setnew'
	 post 'stopword_keyword/:keyword' => 'proposed_keywords#setStopword'


 get ':controller(/:action(/:id(.:format)))'
 post ':controller(/:action(/:id(.:format)))'

end

makeRoutes

#scope  '/siena2' do
#	makeRoutes
#end


end

app/models/related_content.rb
require 'file_helper'


class RelatedContent < ActiveRecord::Base


	belongs_to :node

	UPLOAD_DIR_REL = "relatedContents"
	UPLOAD_DIR = "#{Rails.root.to_s}/public/#{UPLOAD_DIR_REL}"

	def uploadedFiles
			dirname = "#{UPLOAD_DIR}/#{id}"
			Dir.mkdir(dirname) if not File.exists?(dirname)
			res = Array.new
			Dir.entries(dirname).each do |fn|
				res.push(fn)  if File.ftype("#{dirname}/#{fn}")=='file'
			end	
			return res

	end	

	def  deleteFile(filename)
			dirname = "#{UPLOAD_DIR}/#{id}"
			return if not File.exists?(dirname)
			file = "#{dirname}/#{filename}"
			File.delete(file) if File.exists?(file)
			#put filename = "" if it is deleted
			if self.filename == filename
				self.filename = "" 
				self.save
			end
	end


end

app/controllers/related_contents_controller.rb
class RelatedContentsController < ApplicationController
 before_filter(:only => [:index] ) { |c| c.auth  [ {:types =>  [User::ADMIN]  }]  }
 #before_filter(:only => [:listByNodeAndRecover] ) { |c| c.auth  [ {:types =>  [User::ALU]  }]  }
 before_filter(:only => [:show,:listByNodeAndRecover] ) { |c| c.auth nil }
 #NOW all teachers can modify , delete and craete any related content to the nodes	
 before_filter(:only => [:new, :create, :edit, :update, :destroy, :saveUploadFile, :uploadFile,  :deleteFile, :mainFile ] ) { |c| c.auth  [ {:types =>  [User::PROF, User::ADMIN]  }]  }




	layout :green_web

  # GET /related_contents
  # GET /related_contents.xml
  def index
		@related_contents = RelatedContent.includes(node: :course)
	  if params[:id] && params['id']!=""
  	  @related_contents = @related_contents.where('id = ?', params[:id])
  	end
	  if params[:description] && params['description']!=""
  	  @related_contents = @related_contents.where('description LIKE ?', "%#{params[:description]}%")
  	end
	  if params[:filename] && params['filename']!=""
  	  @related_contents = @related_contents.where('filename LIKE ?', "%#{params[:filename]}%")
  	end
	  if params[:node_name] && params['node_name']!=""
			@related_contents = @related_contents.references(:node)
  	  @related_contents = @related_contents.where('nodes.content LIKE ?', "%#{params[:node_name]}%")
  	end
   	@related_contents = @related_contents.paginate(page: params[:page], per_page: 20).order('related_contents.created_at DESC')
  end


	def listByNodeAndRecover
    @related_contents = RelatedContent.where(node_id: params[:node_id], recover: params[:recover])
		render
	end


  # GET /related_contents/1
  # GET /related_contents/1.xml
  def show
    @related_content = RelatedContent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @related_content }
    end
  end

  # GET /related_contents/new
  # GET /related_contents/new.xml
  def new
    @related_content = RelatedContent.new
		@related_content.node_id = params[:node_id]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @related_content }
    end
  end

  # GET /related_contents/1/edit
  def edit
    @related_content = RelatedContent.find(params[:id])
  end


	def uploadFile
    @related_content = RelatedContent.find(params[:related_content_id])
		render
	end


	def saveUploadFile
		file = params[:uploadFile]
		@related_content = RelatedContent.find(params[:id])
		if(file and  file!="")
			dirname = "#{RelatedContent::UPLOAD_DIR}/#{@related_content.id}"
			FileUtils.mkdir_p(dirname) unless File.exists?(dirname)
      #rename the file if contains no ascii chars
			newfilename = file.original_filename.tr("^a-zA-Z0-9_.-","_")
			newfilefullpath = File.join(dirname, newfilename)
			File.open(newfilefullpath, "wb") { |f| f.write(file.read) }
			if params[:decompress]
			#zip files
				 if newfilename =~ /.zip$/
					require 'zip/zipfilesystem'
					Zip::ZipFile.open(newfilefullpath) do |zipfile|
						zipfile.each do |file|
							fpath = File.join(dirname, file.to_s)
							#zip can have a dir path in the name
							FileUtils.mkdir_p(File.dirname(fpath))
							zipfile.extract(file , fpath ){true}
						end			
					end 
				end

			end
			if(params[:mainFile] || @related_content.uploadedFiles.size==0 )
				@related_content.filename = newfilename
				@related_content.save
			end
		end
    render :action => "edit" 
	end


	def deleteFile
    @related_content = RelatedContent.find(params[:related_content_id])
		@related_content.deleteFile(@related_content.uploadedFiles[params[:name].to_i])
		redirect_to :action => "edit" , :id => @related_content.id
	end

	def mainFile
    @related_content = RelatedContent.find(params[:related_content_id])
		@related_content.filename = @related_content.uploadedFiles[params[:name].to_i]
		@related_content.save
		render :action => "edit" 
	end

  # POST /related_contents
  # POST /related_contents.xml
  def create
    @related_content = RelatedContent.new(rc_params)
    if @related_content.save
      flash[:notice] = t('relatedcontent_created_success')
			redirect_to :action => "edit" , :id => @related_content.id
    else
       render :action => "new" 
    end
  end

  # PUT /related_contents/1
  # PUT /related_contents/1.xml
  def update
    @related_content = RelatedContent.find(params[:id])
      if @related_content.update(rc_params)
        flash[:notice] = t('relatedcontent_updated_success')
        redirect_to edit_related_content_path(@related_content) 
      else
         render :action => "edit" 
      end
  end

  # DELETE /related_contents/1
  # DELETE /related_contents/1.xml
  def destroy
    @related_content = RelatedContent.find(params[:id])
    @related_content.destroy
    dirname = "#{RelatedContent::UPLOAD_DIR}/#{@related_content.id}"
    FileUtils.rm_rf  dirname	
    redirect_to @related_content.node	  

end


  def view_as_html 
	rcid = params[:related_content_id]
	filename = params[:filename]	
	dirname = "#{RelatedContent::UPLOAD_DIR}/#{rcid}"
	if filename =~ /html$/ || filename =~ /htm$/
		ActiveRecord::Base.logger.warn("*******************noko")	
		doc =  Nokogiri::HTML(File.read(File.join(dirname,filename)))
		@html_head_section = doc.search("head")
		@html_body_section = doc.search("body")
		render :layout => 'related_contents'
	
	else
		send_file   File.join(dirname, filename)
	end
	
  end	

	private

	def rc_params
			params.require(:related_content).permit(:description, :filename, :recover, :node_id)
	end


end

app/helpers/related_contents_helper.rb
module RelatedContentsHelper
end

app/views/related_contents/edit.html.erb
<h1><%= t('edit_related_content') %> </h1>

<%= form_for(@related_content) do |f| %>
  	  <% if @related_content.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_update, :count => @related_content.errors.count %></h2>	
	      <ul>
	      <% @related_content.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


  <p>
   <%= t('main_file') %><br />
    <%= @related_content.filename %>
  </p>
  <p>
   <%= t('recuperation') %> <br />
    <%= f.check_box :recover %>
  </p>
  <p>
   <%= t(:description) %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit t('update') %>
  </p>
<% end %>

<br />

<b><%= t('uploaded_files') %>:</b>
<table>

<% i = 0 %>
<% @related_content.uploadedFiles.each do |n| %>
  <tr>
    <td><%=h n %></td>
    <td><%= link_to t('delete'),:action => "deleteFile" , :related_content_id => @related_content.id , :name => i %></td>
    <td><%= link_to t('main_file'),:action => "mainFile" , :related_content_id => @related_content.id , :name => i %></td>
  </tr>
<% i+=1 %>

<% end %>
</table>
<%= link_to  t(:upload_file), :controller=>"related_contents",  :action=>"uploadFile",  :related_content_id=>@related_content.id %>



<br />


<%= link_to t('view'), @related_content %> |
<%= link_to t('view_assoc_node'), :controller => "nodes" , :action => "show", :id => @related_content.node_id %>
<% if @related_content.node.teacher_id == session[:useraccount_id] %>
|<%= link_to t('edit_assoc_node'), :controller => "nodes" , :action => "edit", :id => @related_content.node_id %>
<% end %>

app/views/related_contents/index.html.erb
<h1><%= t('related_content_list') %></h1>

<div class="wice-grid-container" id="grid"><table  class="table-striped table-bordered table wice-grid">
<thead><tr  class="wice-grid-title-row">

			<th> <%= t('id') %> </th>	
			<th> <%= t('description') %> </th>	
			<th> <%= t('filename') %> </th>	
			<th> <%= t('node') %> </th>	
			<th> <%= t('course') %> </th>	
			<th> <%= t(:view) %> </th>	
			<th> <%= t(:edit) %> </th>	
			<th> <%= t(:delete) %> </th>	
		</tr>	
    <tr>		
		<%= form_tag({}, method: :get) do %>
   		<th><%= text_field_tag :id, params[:id] %></th>
   		<th><%= text_field_tag :description, params[:description] %></th>
   		<th><%= text_field_tag :filename, params[:filename] %></th>
   		<th><%= text_field_tag :node_name, params[:node_name] %></th>
   		<th>&nbsp;</th>
   		<th>&nbsp;</th>
   		<th>&nbsp;</th>
   		<th>&nbsp;</th>
   		<th class="submit" ><%= submit_tag 'Search', name: nil%></th>
		<% end %>
		</tr>

  </thead>
  <tbody>

 <% for rc in @related_contents %>
    <tr>
	<td>
		<%=	rc.id %>
	</td>	
	<td>
		<%=	rc.description %>
	</td>	
	<td>
		<%=	rc.filename %>
	</td>	
	<td>
		<%=	rc.node.content %>
	</td>	
	<td>
		<%=	rc.node.course.name %>
	</td>	
	<td>
		<%= link_to t('view'), rc%>
	</td>	
	<td>
		<%= link_to t('edit'), edit_related_content_path(rc)%>
	</td>	
	<td>
		<%= link_to t('delete'), rc, :confirm => t('deletion_confirmation'), :method => :delete %>
	</td>	
     </tr>       
 <% end %>


  </tbody>
</table>

<%= will_paginate @related_contents %>

</div>

app/views/related_contents/listByNodeAndRecover.html.erb
<h1> <%= t('related_content_list_node' , :node => Node.find(params[:node_id]).content) %>  </h1>

<% if params[:recover] == "true" %>
	<p><b> <%= t('recuperation') %>  </b></p>
<% end %>

<% if @related_contents.size() > 0 %>
<table>
  <tr>
    <th><%= t('filename') %></th>
    <th><%= t(:description) %></th>
  </tr>

<% @related_contents.each do |related_content| %>
  <tr>
    <td><a href=<%= "/relatedContents/#{related_content.id}/#{related_content.filename}" %>><%=h related_content.filename %></a></td>
    <td><%=h related_content.description %></td>
    <td><%= link_to "HTML" , :action =>  "view_as_html", :related_content_id => related_content.id , :filename => related_content.filename  %></td>
  </tr>
<% end %>
</table>

<% else %>
	<b> No hay contenidos </b>
<% end %>

<br />

app/views/related_contents/new.html.erb
<h1><%=  t('node_new_related_content') %> </h1>

<%= form_for(@related_content) do |f| %>
  	  <% if @related_content.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_save, :count => @related_content.errors.count %></h2>	
	
	      <ul>
	      <% @related_content.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

    <%= f.hidden_field :node_id %>

  <p>
		<%=  t('recuperation') %><br />
    <%= f.check_box :recover %>
  </p>
  <p>
    <%=  t(:description) %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit t(:create) %>
  </p>
<% end %>

<%= link_to t(:back), edit_node_path(@related_content.node) %>

app/views/related_contents/show.html.erb
<p>
  <b><%=  t('filename') %>:</b>
  <%=h @related_content.filename %>
	<br/>
	<a href=<%= "/#{RelatedContent::UPLOAD_DIR_REL}/#{@related_content.id}/#{@related_content.filename}" %>><%=h @related_content.filename %></a>

</p>

<p>
  <b><%=  t('recuperation') %>:</b>
  <%=h @related_content.recover %>
</p>

<p>
  <b><%=  t(:description) %>:</b>
  <%=h @related_content.description %>
</p>

<b><%=  t('uploaded_files') %></b>
<table>

<% @related_content.uploadedFiles.each do |n| %>
  <tr>
    <td><%=h n %></td>
  </tr>

<% end %>
</table>

<%= link_to t(:edit), edit_related_content_path(@related_content) %> |
<%= link_to t('view_assoc_node'), :controller => "nodes" , :action => "show", :id => @related_content.node_id %> 
<% if @related_content.node.teacher_id == session[:useraccount_id] %>
|<%= link_to t('edit_assoc_node'), :controller => "nodes" , :action => "edit", :id => @related_content.node_id %>
<% end %>

app/views/related_contents/uploadFile.html.erb
<h1> <%=  t('upload_file') %> </h1>


<%= form_tag({:action => 'saveUploadFile'}, {:method => :post , :multipart => true }) do |f|  %>
<%= hidden_field_tag :id , @related_content.id   %>


  <p>
    <%=  t('filename') %><br />
    <%= file_field_tag :uploadFile %>
  </p>

  <p>
   <%=  t('main_file') %> <br />
    <%= check_box_tag :mainFile %>
  </p>
  <p>
   <%=  t('decompress') %> <br />
    <%= check_box_tag :decompress %>
  </p>

  <p>
    <%= submit_tag t('upload_file') %>
  </p>
<% end %>

app/views/related_contents/view_as_html.html.erb
<% content_for :head do %>
  <%=  raw @html_header_section%>
<% end %>

  <%=  raw @html_body_section%>